### ISSUE TITLE
docs: Docker compose deployment

### ISSUE THREAD

**Issue by ilyasKerbal** [APIParkLab/APIPark#184]
### Current State

While following the docker compose guide, I got the following error:

```Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "/nsqd --data-path=/data": stat /nsqd --data-path=/data: no such file or directory: unknown```

Here is the deployment for the  `apipark-nsq` service:
```
  apipark-nsq:
    container_name: apipark-nsq
    image: nsqio/nsq:v1.3.0
    hostname: apipark-nsq
    privileged: true
    restart: always
    command:
      - /nsqd --data-path=/data
    ports:
      - 4150:4150
      - 4151:4151
    volumes:
      - ./var/lib/apipark/nsq:/data
    networks:
      - apipark
```

### Desired State

Fix the error

**Comment by Dot-Liu** [comment]
Ok. We will try to reproduce it first and get back to you as soon as possible.

**Comment by Dot-Liu** [comment]
Please update the nsq service as follows
```
apipark-nsq:
    container_name: apipark-nsq
    image: nsqio/nsq:v1.3.0
    hostname: apipark-nsq
    privileged: true
    restart: always
    command:
      - /nsqd
    ports:
      - 4150:4150
      - 4151:4151
    volumes:
      - /var/lib/apipark/nsq:/data
    networks:
      - apipark
```
